services:
  - type: web
    name: buildpro-connect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/stats
    autoDeploy: true

  - type: pserv
    name: buildpro-db
    env: postgresql
    plan: free
    ipAllowList: [] 